#!/usr/bin/env python3
"""The validator's sample report: this repo's own strategies, failures
included (roadmap V3 demo). Writes docs/VALIDATION_SAMPLE.md.

Each crypto standard-book strategy is backtested alone on BTC/USDT at its
own timeframe over one pinned two-year window, the trades are gathered into
one file (so PBO can rank the family), and `validate-trades` judges them
exactly as it would anyone else's.

    BOT_DB_PATH=/tmp/x/trading.db python3 scripts/sample_validation.py

Needs the market data (fetched once, then cached). --trials is the number
of strategies the standard gate declares, a LOWER bound on what was tried:
the experiment registry holds more variants than that.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from bot.backtest import Backtester  # noqa: E402
from bot.data import fetch_history  # noqa: E402
from bot.validator import render_markdown, validate  # noqa: E402
from config import MarketSpec  # noqa: E402

SYMBOL = "BTC/USDT"
START, END = "2023-10-01", "2025-10-01"
REGIME_START = "2023-01-01"          # 200 daily bars before START for the labels
STRATEGIES = {"turtle_trend": "1h", "connors_meanrev": "4h",
              "vwap_scalper": "15m", "ts_momentum": "4h"}
TRIALS = 5                           # strategies in experiments/standard_gate.toml
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "docs", "VALIDATION_SAMPLE.md")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()
    family = {}
    for name, tf in STRATEGIES.items():
        spec = MarketSpec("crypto", SYMBOL, tf)
        df = fetch_history(spec, start=START, end=END)
        res = Backtester().run(spec, df, strategy=name)
        family[f"{name} ({tf})"] = {"trades": res.trades}
        print(f"[sample] {name} {tf}: {len(res.trades)} trades")
    daily = fetch_history(MarketSpec("crypto", SYMBOL, "1d"), start=REGIME_START, end=END)
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "own_strategies.json")
        with open(path, "w") as fh:
            json.dump({"strategy": family}, fh, default=str)
        report = validate(path, trials=TRIALS, daily=daily)
    report["input"] = f"this repo's strategies, {SYMBOL}, {START} to {END}"
    report["source"] = "this repo's backtester (one strategy per run)"
    title, body = render_markdown(report).split("\n", 1)
    note = ("\n*The validator run on this repository's own standard-book strategies "
            "(roadmap V3 demo). Each was backtested alone on BTC/USDT at its own "
            "timeframe, after fees, over the same two years; the trades were then judged "
            f"exactly as anyone else's would be. `--trials {TRIALS}` counts only the "
            "strategies the gate declares, so the Deflated Sharpe here is generous.*\n")
    with open(args.out, "w") as fh:
        fh.write("<!-- generated by scripts/sample_validation.py; do not edit by hand -->\n"
                 + title + "\n" + note + body)
    print(f"[sample] wrote {args.out}")


if __name__ == "__main__":
    main()
